version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker:
    build: .
    command: celery -A backend worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:6